package org.yynn.resm.model;



/**
 * Addressarea generated by MyEclipse - Hibernate Tools
 */

public class Addressarea extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private String name;
     private String description;


    // Constructors

    /** default constructor */
    public Addressarea() {
    }

	/** minimal constructor */
    public Addressarea(Project project, String name) {
        this.project = project;
        this.name = name;
    }
    
    /** full constructor */
    public Addressarea(Project project, String name, String description) {
        this.project = project;
        this.name = name;
        this.description = description;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}