package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Basehousetype generated by MyEclipse - Hibernate Tools
 */

public class Basehousetype extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String description;
     private Set housetypes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Basehousetype() {
    }

	/** minimal constructor */
    public Basehousetype(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Basehousetype(String name, String description, Set housetypes) {
        this.name = name;
        this.description = description;
        this.housetypes = housetypes;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getHousetypes() {
        return this.housetypes;
    }
    
    public void setHousetypes(Set housetypes) {
        this.housetypes = housetypes;
    }
   








}