package org.yynn.resm.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Buildingproject generated by MyEclipse - Hibernate Tools
 */

public class Buildingproject extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Fitmentlevel fitmentlevel;
     private Project project;
     private Buildtype buildtype;
     private Pipenetinfo pipenetinfo;
     private Housingproject housingproject;
     private Buildstruct buildstruct;
     private String name;
     private Float height;
     private Integer housecount;
     private String remark;
     private Date builddate;
     private Set houseprojects = new HashSet(0);


    // Constructors

    /** default constructor */
    public Buildingproject() {
    }

	/** minimal constructor */
    public Buildingproject(Project project, Housingproject housingproject, String name) {
        this.project = project;
        this.housingproject = housingproject;
        this.name = name;
    }
    
    /** full constructor */
    public Buildingproject(Fitmentlevel fitmentlevel, Project project, Buildtype buildtype, Pipenetinfo pipenetinfo, Housingproject housingproject, Buildstruct buildstruct, String name, Float height, Integer housecount, String remark, Date builddate, Set houseprojects) {
        this.fitmentlevel = fitmentlevel;
        this.project = project;
        this.buildtype = buildtype;
        this.pipenetinfo = pipenetinfo;
        this.housingproject = housingproject;
        this.buildstruct = buildstruct;
        this.name = name;
        this.height = height;
        this.housecount = housecount;
        this.remark = remark;
        this.builddate = builddate;
        this.houseprojects = houseprojects;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Fitmentlevel getFitmentlevel() {
        return this.fitmentlevel;
    }
    
    public void setFitmentlevel(Fitmentlevel fitmentlevel) {
        this.fitmentlevel = fitmentlevel;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public Buildtype getBuildtype() {
        return this.buildtype;
    }
    
    public void setBuildtype(Buildtype buildtype) {
        this.buildtype = buildtype;
    }

    public Pipenetinfo getPipenetinfo() {
        return this.pipenetinfo;
    }
    
    public void setPipenetinfo(Pipenetinfo pipenetinfo) {
        this.pipenetinfo = pipenetinfo;
    }

    public Housingproject getHousingproject() {
        return this.housingproject;
    }
    
    public void setHousingproject(Housingproject housingproject) {
        this.housingproject = housingproject;
    }

    public Buildstruct getBuildstruct() {
        return this.buildstruct;
    }
    
    public void setBuildstruct(Buildstruct buildstruct) {
        this.buildstruct = buildstruct;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Float getHeight() {
        return this.height;
    }
    
    public void setHeight(Float height) {
        this.height = height;
    }

    public Integer getHousecount() {
        return this.housecount;
    }
    
    public void setHousecount(Integer housecount) {
        this.housecount = housecount;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getBuilddate() {
        return this.builddate;
    }
    
    public void setBuilddate(Date builddate) {
        this.builddate = builddate;
    }

    public Set getHouseprojects() {
        return this.houseprojects;
    }
    
    public void setHouseprojects(Set houseprojects) {
        this.houseprojects = houseprojects;
    }
   








}