package org.yynn.resm.model;

import java.util.Date;


/**
 * Callcustomer generated by MyEclipse - Hibernate Tools
 */

public class Callcustomer extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Inforchannel inforchannel;
     private Problem problem;
     private Project project;
     private Housetype housetype;
     private Purpose purpose;
     private Date cdate;
     private String name;
     private String address;
     private String contact;
     private String company;


    // Constructors

    /** default constructor */
    public Callcustomer() {
    }

	/** minimal constructor */
    public Callcustomer(Project project, Date cdate, String name) {
        this.project = project;
        this.cdate = cdate;
        this.name = name;
    }
    
    /** full constructor */
    public Callcustomer(Inforchannel inforchannel, Problem problem, Project project, Housetype housetype, Purpose purpose, Date cdate, String name, String address, String contact, String company) {
        this.inforchannel = inforchannel;
        this.problem = problem;
        this.project = project;
        this.housetype = housetype;
        this.purpose = purpose;
        this.cdate = cdate;
        this.name = name;
        this.address = address;
        this.contact = contact;
        this.company = company;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Inforchannel getInforchannel() {
        return this.inforchannel;
    }
    
    public void setInforchannel(Inforchannel inforchannel) {
        this.inforchannel = inforchannel;
    }

    public Problem getProblem() {
        return this.problem;
    }
    
    public void setProblem(Problem problem) {
        this.problem = problem;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public Housetype getHousetype() {
        return this.housetype;
    }
    
    public void setHousetype(Housetype housetype) {
        this.housetype = housetype;
    }

    public Purpose getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(Purpose purpose) {
        this.purpose = purpose;
    }

    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
   








}