package org.yynn.resm.model;

import java.util.Date;


/**
 * Commision generated by MyEclipse - Hibernate Tools
 */

public class Commision extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private Integer salesum;
     private Integer pcommision;
     private Date blancedate;
     private Integer blancecommision;
     private Integer lackcommision;
     private Date recorddate;
     private String remark;


    // Constructors

    /** default constructor */
    public Commision() {
    }

	/** minimal constructor */
    public Commision(Project project, Integer salesum, Integer pcommision, Date blancedate, Integer blancecommision, Integer lackcommision, Date recorddate) {
        this.project = project;
        this.salesum = salesum;
        this.pcommision = pcommision;
        this.blancedate = blancedate;
        this.blancecommision = blancecommision;
        this.lackcommision = lackcommision;
        this.recorddate = recorddate;
    }
    
    /** full constructor */
    public Commision(Project project, Integer salesum, Integer pcommision, Date blancedate, Integer blancecommision, Integer lackcommision, Date recorddate, String remark) {
        this.project = project;
        this.salesum = salesum;
        this.pcommision = pcommision;
        this.blancedate = blancedate;
        this.blancecommision = blancecommision;
        this.lackcommision = lackcommision;
        this.recorddate = recorddate;
        this.remark = remark;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public Integer getSalesum() {
        return this.salesum;
    }
    
    public void setSalesum(Integer salesum) {
        this.salesum = salesum;
    }

    public Integer getPcommision() {
        return this.pcommision;
    }
    
    public void setPcommision(Integer pcommision) {
        this.pcommision = pcommision;
    }

    public Date getBlancedate() {
        return this.blancedate;
    }
    
    public void setBlancedate(Date blancedate) {
        this.blancedate = blancedate;
    }

    public Integer getBlancecommision() {
        return this.blancecommision;
    }
    
    public void setBlancecommision(Integer blancecommision) {
        this.blancecommision = blancecommision;
    }

    public Integer getLackcommision() {
        return this.lackcommision;
    }
    
    public void setLackcommision(Integer lackcommision) {
        this.lackcommision = lackcommision;
    }

    public Date getRecorddate() {
        return this.recorddate;
    }
    
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}