package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Customer generated by MyEclipse - Hibernate Tools
 */

public class Customer extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private String name;
     private String address;
     private String contact;
     private String company;
     private Set visitcustomers = new HashSet(0);


    // Constructors

    /** default constructor */
    public Customer() {
    }

	/** minimal constructor */
    public Customer(Integer id, Project project, String name) {
        this.id = id;
        this.project = project;
        this.name = name;
    }
    
    /** full constructor */
    public Customer(Integer id, Project project, String name, String address, String contact, String company, Set visitcustomers) {
        this.id = id;
        this.project = project;
        this.name = name;
        this.address = address;
        this.contact = contact;
        this.company = company;
        this.visitcustomers = visitcustomers;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    public Set getVisitcustomers() {
        return this.visitcustomers;
    }
    
    public void setVisitcustomers(Set visitcustomers) {
        this.visitcustomers = visitcustomers;
    }
   








}