package org.yynn.resm.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Housingproject generated by MyEclipse - Hibernate Tools
 */

public class Housingproject extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private String name;
     private String address;
     private Integer gharea;
     private Integer jzarea;
     private Integer jzjdarea;
     private Integer dlgcarea;
     private Integer lharea;
     private Short jzmd;
     private Short lhl;
     private Short rjl;
     private Date devdate;
     private String image;
     private Integer buildingcount;
     private Integer housecount;
     private Integer carplace;
     private Integer storeroom;
     private Set houseprojects = new HashSet(0);
     private Set buildingprojects = new HashSet(0);


    // Constructors

    /** default constructor */
    public Housingproject() {
    }

	/** minimal constructor */
    public Housingproject(Project project, String name, String address) {
        this.project = project;
        this.name = name;
        this.address = address;
    }
    
    /** full constructor */
    public Housingproject(Project project, String name, String address, Integer gharea, Integer jzarea, Integer jzjdarea, Integer dlgcarea, Integer lharea, Short jzmd, Short lhl, Short rjl, Date devdate, String image, Integer buildingcount, Integer housecount, Integer carplace, Integer storeroom, Set houseprojects, Set buildingprojects) {
        this.project = project;
        this.name = name;
        this.address = address;
        this.gharea = gharea;
        this.jzarea = jzarea;
        this.jzjdarea = jzjdarea;
        this.dlgcarea = dlgcarea;
        this.lharea = lharea;
        this.jzmd = jzmd;
        this.lhl = lhl;
        this.rjl = rjl;
        this.devdate = devdate;
        this.image = image;
        this.buildingcount = buildingcount;
        this.housecount = housecount;
        this.carplace = carplace;
        this.storeroom = storeroom;
        this.houseprojects = houseprojects;
        this.buildingprojects = buildingprojects;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getGharea() {
        return this.gharea;
    }
    
    public void setGharea(Integer gharea) {
        this.gharea = gharea;
    }

    public Integer getJzarea() {
        return this.jzarea;
    }
    
    public void setJzarea(Integer jzarea) {
        this.jzarea = jzarea;
    }

    public Integer getJzjdarea() {
        return this.jzjdarea;
    }
    
    public void setJzjdarea(Integer jzjdarea) {
        this.jzjdarea = jzjdarea;
    }

    public Integer getDlgcarea() {
        return this.dlgcarea;
    }
    
    public void setDlgcarea(Integer dlgcarea) {
        this.dlgcarea = dlgcarea;
    }

    public Integer getLharea() {
        return this.lharea;
    }
    
    public void setLharea(Integer lharea) {
        this.lharea = lharea;
    }

    public Short getJzmd() {
        return this.jzmd;
    }
    
    public void setJzmd(Short jzmd) {
        this.jzmd = jzmd;
    }

    public Short getLhl() {
        return this.lhl;
    }
    
    public void setLhl(Short lhl) {
        this.lhl = lhl;
    }

    public Short getRjl() {
        return this.rjl;
    }
    
    public void setRjl(Short rjl) {
        this.rjl = rjl;
    }

    public Date getDevdate() {
        return this.devdate;
    }
    
    public void setDevdate(Date devdate) {
        this.devdate = devdate;
    }

    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    public Integer getBuildingcount() {
        return this.buildingcount;
    }
    
    public void setBuildingcount(Integer buildingcount) {
        this.buildingcount = buildingcount;
    }

    public Integer getHousecount() {
        return this.housecount;
    }
    
    public void setHousecount(Integer housecount) {
        this.housecount = housecount;
    }

    public Integer getCarplace() {
        return this.carplace;
    }
    
    public void setCarplace(Integer carplace) {
        this.carplace = carplace;
    }

    public Integer getStoreroom() {
        return this.storeroom;
    }
    
    public void setStoreroom(Integer storeroom) {
        this.storeroom = storeroom;
    }

    public Set getHouseprojects() {
        return this.houseprojects;
    }
    
    public void setHouseprojects(Set houseprojects) {
        this.houseprojects = houseprojects;
    }

    public Set getBuildingprojects() {
        return this.buildingprojects;
    }
    
    public void setBuildingprojects(Set buildingprojects) {
        this.buildingprojects = buildingprojects;
    }
   








}