package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Housetypeinfo generated by MyEclipse - Hibernate Tools
 */

public class Housetypeinfo extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String description;
     private Set houseprojects = new HashSet(0);


    // Constructors

    /** default constructor */
    public Housetypeinfo() {
    }

	/** minimal constructor */
    public Housetypeinfo(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Housetypeinfo(String name, String description, Set houseprojects) {
        this.name = name;
        this.description = description;
        this.houseprojects = houseprojects;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getHouseprojects() {
        return this.houseprojects;
    }
    
    public void setHouseprojects(Set houseprojects) {
        this.houseprojects = houseprojects;
    }
   








}