package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Houseproject generated by MyEclipse - Hibernate Tools
 */

public class Houseproject extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private Houseform houseform;
     private Housingproject housingproject;
     private Housetypeinfo housetypeinfo;
     private Additionform additionform;
     private Buildingproject buildingproject;
     private Integer floor;
     private Integer unit;
     private String no;
     private Float height;
     private String direction;
     private Float additionprice;
     private Float inarea;
     private Float balcony;
     private Float apportion;
     private Float sellarea;
     private Float unitprice;
     private Float totalprice;
     private String remark;
     private Set saleinfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public Houseproject() {
    }

	/** minimal constructor */
    public Houseproject(Project project, Housingproject housingproject, Buildingproject buildingproject, String no) {
        this.project = project;
        this.housingproject = housingproject;
        this.buildingproject = buildingproject;
        this.no = no;
    }
    
    /** full constructor */
    public Houseproject(Project project, Houseform houseform, Housingproject housingproject, Housetypeinfo housetypeinfo, Additionform additionform, Buildingproject buildingproject, Integer floor, Integer unit, String no, Float height, String direction, Float additionprice, Float inarea, Float balcony, Float apportion, Float sellarea, Float unitprice, Float totalprice, String remark, Set saleinfos) {
        this.project = project;
        this.houseform = houseform;
        this.housingproject = housingproject;
        this.housetypeinfo = housetypeinfo;
        this.additionform = additionform;
        this.buildingproject = buildingproject;
        this.floor = floor;
        this.unit = unit;
        this.no = no;
        this.height = height;
        this.direction = direction;
        this.additionprice = additionprice;
        this.inarea = inarea;
        this.balcony = balcony;
        this.apportion = apportion;
        this.sellarea = sellarea;
        this.unitprice = unitprice;
        this.totalprice = totalprice;
        this.remark = remark;
        this.saleinfos = saleinfos;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public Houseform getHouseform() {
        return this.houseform;
    }
    
    public void setHouseform(Houseform houseform) {
        this.houseform = houseform;
    }

    public Housingproject getHousingproject() {
        return this.housingproject;
    }
    
    public void setHousingproject(Housingproject housingproject) {
        this.housingproject = housingproject;
    }

    public Housetypeinfo getHousetypeinfo() {
        return this.housetypeinfo;
    }
    
    public void setHousetypeinfo(Housetypeinfo housetypeinfo) {
        this.housetypeinfo = housetypeinfo;
    }

    public Additionform getAdditionform() {
        return this.additionform;
    }
    
    public void setAdditionform(Additionform additionform) {
        this.additionform = additionform;
    }

    public Buildingproject getBuildingproject() {
        return this.buildingproject;
    }
    
    public void setBuildingproject(Buildingproject buildingproject) {
        this.buildingproject = buildingproject;
    }

    public Integer getFloor() {
        return this.floor;
    }
    
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    public Integer getUnit() {
        return this.unit;
    }
    
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }

    public Float getHeight() {
        return this.height;
    }
    
    public void setHeight(Float height) {
        this.height = height;
    }

    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }

    public Float getAdditionprice() {
        return this.additionprice;
    }
    
    public void setAdditionprice(Float additionprice) {
        this.additionprice = additionprice;
    }

    public Float getInarea() {
        return this.inarea;
    }
    
    public void setInarea(Float inarea) {
        this.inarea = inarea;
    }

    public Float getBalcony() {
        return this.balcony;
    }
    
    public void setBalcony(Float balcony) {
        this.balcony = balcony;
    }

    public Float getApportion() {
        return this.apportion;
    }
    
    public void setApportion(Float apportion) {
        this.apportion = apportion;
    }

    public Float getSellarea() {
        return this.sellarea;
    }
    
    public void setSellarea(Float sellarea) {
        this.sellarea = sellarea;
    }

    public Float getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Float unitprice) {
        this.unitprice = unitprice;
    }

    public Float getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(Float totalprice) {
        this.totalprice = totalprice;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set getSaleinfos() {
        return this.saleinfos;
    }
    
    public void setSaleinfos(Set saleinfos) {
        this.saleinfos = saleinfos;
    }
   








}