package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Housetype generated by MyEclipse - Hibernate Tools
 */

public class Housetype extends org.yynn.resm.model.BaseModel implements java.io.Serializable {

	// Fields

	private Integer id;

	private Project project;

	private Basehousetype basehousetype;

	private Integer max;

	private Integer min;

	private Set callcustomers = new HashSet(0);

	private Set visitcustomers = new HashSet(0);

	// Constructors

	/** default constructor */
	public Housetype() {
	}

	/** minimal constructor */
	public Housetype(Project project, Basehousetype basehousetype, Integer max, Integer min) {
		this.project = project;
		this.basehousetype = basehousetype;
		this.max = max;
		this.min = min;
	}

	/** full constructor */
	public Housetype(Project project, Basehousetype basehousetype, Integer max, Integer min, Set callcustomers,
			Set visitcustomers) {
		this.project = project;
		this.basehousetype = basehousetype;
		this.max = max;
		this.min = min;
		this.callcustomers = callcustomers;
		this.visitcustomers = visitcustomers;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Basehousetype getBasehousetype() {
		return this.basehousetype;
	}

	public void setBasehousetype(Basehousetype basehousetype) {
		this.basehousetype = basehousetype;
	}

	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

	public Integer getMin() {
		return this.min;
	}

	public void setMin(Integer min) {
		this.min = min;
	}

	public Set getCallcustomers() {
		return this.callcustomers;
	}

	public void setCallcustomers(Set callcustomers) {
		this.callcustomers = callcustomers;
	}

	public Set getVisitcustomers() {
		return this.visitcustomers;
	}

	public void setVisitcustomers(Set visitcustomers) {
		this.visitcustomers = visitcustomers;
	}

	public String getDisplayValue() {
		return basehousetype.getName() + "[" + min + "-" + max + "]";
	}

}