package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Project generated by MyEclipse - Hibernate Tools
 */

public class Project extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private String no;
     private String leaderName;
     private String password;
     private String level;
     private Set visitcustomers = new HashSet(0);
     private Set housetypes = new HashSet(0);
     private Set houseprojects = new HashSet(0);
     private Set sellers = new HashSet(0);
     private Set customers = new HashSet(0);
     private Set callcustomers = new HashSet(0);
     private Set housingprojects = new HashSet(0);
     private Set buildingprojects = new HashSet(0);
     private Set addressareas = new HashSet(0);
     private Set commisions = new HashSet(0);


    // Constructors

    /** default constructor */
    public Project() {
    }

	/** minimal constructor */
    public Project(String no, String password, String level) {
        this.no = no;
        this.password = password;
        this.level = level;
    }
    
    /** full constructor */
    public Project(String no, String leaderName, String password, String level, Set visitcustomers, Set housetypes, Set houseprojects, Set sellers, Set customers, Set callcustomers, Set housingprojects, Set buildingprojects, Set addressareas, Set commisions) {
        this.no = no;
        this.leaderName = leaderName;
        this.password = password;
        this.level = level;
        this.visitcustomers = visitcustomers;
        this.housetypes = housetypes;
        this.houseprojects = houseprojects;
        this.sellers = sellers;
        this.customers = customers;
        this.callcustomers = callcustomers;
        this.housingprojects = housingprojects;
        this.buildingprojects = buildingprojects;
        this.addressareas = addressareas;
        this.commisions = commisions;
    }

   
    // Property accessors

    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }

    public String getLeaderName() {
        return this.leaderName;
    }
    
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    public Set getVisitcustomers() {
        return this.visitcustomers;
    }
    
    public void setVisitcustomers(Set visitcustomers) {
        this.visitcustomers = visitcustomers;
    }

    public Set getHousetypes() {
        return this.housetypes;
    }
    
    public void setHousetypes(Set housetypes) {
        this.housetypes = housetypes;
    }

    public Set getHouseprojects() {
        return this.houseprojects;
    }
    
    public void setHouseprojects(Set houseprojects) {
        this.houseprojects = houseprojects;
    }

    public Set getSellers() {
        return this.sellers;
    }
    
    public void setSellers(Set sellers) {
        this.sellers = sellers;
    }

    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }

    public Set getCallcustomers() {
        return this.callcustomers;
    }
    
    public void setCallcustomers(Set callcustomers) {
        this.callcustomers = callcustomers;
    }

    public Set getHousingprojects() {
        return this.housingprojects;
    }
    
    public void setHousingprojects(Set housingprojects) {
        this.housingprojects = housingprojects;
    }

    public Set getBuildingprojects() {
        return this.buildingprojects;
    }
    
    public void setBuildingprojects(Set buildingprojects) {
        this.buildingprojects = buildingprojects;
    }

    public Set getAddressareas() {
        return this.addressareas;
    }
    
    public void setAddressareas(Set addressareas) {
        this.addressareas = addressareas;
    }

    public Set getCommisions() {
        return this.commisions;
    }
    
    public void setCommisions(Set commisions) {
        this.commisions = commisions;
    }
   








}