package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Saleinfo generated by MyEclipse - Hibernate Tools
 */

public class Saleinfo extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Houseproject houseproject;
     private String earnesttype;
     private Float earnest;
     private Float payfirst;
     private Float paypermonth;
     private String contract;
     private Float payback;
     private String state;
     private Set visitcustomers = new HashSet(0);


    // Constructors

    /** default constructor */
    public Saleinfo() {
    }

	/** minimal constructor */
    public Saleinfo(Houseproject houseproject, String earnesttype, String state) {
        this.houseproject = houseproject;
        this.earnesttype = earnesttype;
        this.state = state;
    }
    
    /** full constructor */
    public Saleinfo(Houseproject houseproject, String earnesttype, Float earnest, Float payfirst, Float paypermonth, String contract, Float payback, String state, Set visitcustomers) {
        this.houseproject = houseproject;
        this.earnesttype = earnesttype;
        this.earnest = earnest;
        this.payfirst = payfirst;
        this.paypermonth = paypermonth;
        this.contract = contract;
        this.payback = payback;
        this.state = state;
        this.visitcustomers = visitcustomers;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Houseproject getHouseproject() {
        return this.houseproject;
    }
    
    public void setHouseproject(Houseproject houseproject) {
        this.houseproject = houseproject;
    }

    public String getEarnesttype() {
        return this.earnesttype;
    }
    
    public void setEarnesttype(String earnesttype) {
        this.earnesttype = earnesttype;
    }

    public Float getEarnest() {
        return this.earnest;
    }
    
    public void setEarnest(Float earnest) {
        this.earnest = earnest;
    }

    public Float getPayfirst() {
        return this.payfirst;
    }
    
    public void setPayfirst(Float payfirst) {
        this.payfirst = payfirst;
    }

    public Float getPaypermonth() {
        return this.paypermonth;
    }
    
    public void setPaypermonth(Float paypermonth) {
        this.paypermonth = paypermonth;
    }

    public String getContract() {
        return this.contract;
    }
    
    public void setContract(String contract) {
        this.contract = contract;
    }

    public Float getPayback() {
        return this.payback;
    }
    
    public void setPayback(Float payback) {
        this.payback = payback;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public Set getVisitcustomers() {
        return this.visitcustomers;
    }
    
    public void setVisitcustomers(Set visitcustomers) {
        this.visitcustomers = visitcustomers;
    }
   








}