package org.yynn.resm.model;

import java.util.HashSet;
import java.util.Set;


/**
 * Seller generated by MyEclipse - Hibernate Tools
 */

public class Seller extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Project project;
     private String no;
     private String name;
     private String sex;
     private Integer age;
     private String degree;
     private String nativePlace;
     private String identityno;
     private String position;
     private String telno;
     private String state;
     private Set visitcustomers = new HashSet(0);


    // Constructors

    /** default constructor */
    public Seller() {
    }

	/** minimal constructor */
    public Seller(Project project, String no, String name) {
        this.project = project;
        this.no = no;
        this.name = name;
    }
    
    /** full constructor */
    public Seller(Project project, String no, String name, String sex, Integer age, String degree, String nativePlace, String identityno, String position, String telno, String state, Set visitcustomers) {
        this.project = project;
        this.no = no;
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.degree = degree;
        this.nativePlace = nativePlace;
        this.identityno = identityno;
        this.position = position;
        this.telno = telno;
        this.state = state;
        this.visitcustomers = visitcustomers;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getNativePlace() {
        return this.nativePlace;
    }
    
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    public String getIdentityno() {
        return this.identityno;
    }
    
    public void setIdentityno(String identityno) {
        this.identityno = identityno;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getTelno() {
        return this.telno;
    }
    
    public void setTelno(String telno) {
        this.telno = telno;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public Set getVisitcustomers() {
        return this.visitcustomers;
    }
    
    public void setVisitcustomers(Set visitcustomers) {
        this.visitcustomers = visitcustomers;
    }
   








}