package org.yynn.resm.model;

import java.util.Date;


/**
 * Visitcustomer generated by MyEclipse - Hibernate Tools
 */

public class Visitcustomer extends org.yynn.resm.model.BaseModel implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Inforchannel inforchannel;
     private Seller seller;
     private Problem problem;
     private Project project;
     private Saleinfo saleinfo;
     private Housetype housetype;
     private Purpose purpose;
     private Customer customer;
     private Date cdate;
     private String otherreason;
     private String advice;
     private String dealornot;


    // Constructors

    /** default constructor */
    public Visitcustomer() {
    }

	/** minimal constructor */
    public Visitcustomer(Seller seller, Project project, Date cdate, String dealornot) {
        this.seller = seller;
        this.project = project;
        this.cdate = cdate;
        this.dealornot = dealornot;
    }
    
    /** full constructor */
    public Visitcustomer(Inforchannel inforchannel, Seller seller, Problem problem, Project project, Saleinfo saleinfo, Housetype housetype, Purpose purpose, Customer customer, Date cdate, String otherreason, String advice, String dealornot) {
        this.inforchannel = inforchannel;
        this.seller = seller;
        this.problem = problem;
        this.project = project;
        this.saleinfo = saleinfo;
        this.housetype = housetype;
        this.purpose = purpose;
        this.customer = customer;
        this.cdate = cdate;
        this.otherreason = otherreason;
        this.advice = advice;
        this.dealornot = dealornot;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Inforchannel getInforchannel() {
        return this.inforchannel;
    }
    
    public void setInforchannel(Inforchannel inforchannel) {
        this.inforchannel = inforchannel;
    }

    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }

    public Problem getProblem() {
        return this.problem;
    }
    
    public void setProblem(Problem problem) {
        this.problem = problem;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public Saleinfo getSaleinfo() {
        return this.saleinfo;
    }
    
    public void setSaleinfo(Saleinfo saleinfo) {
        this.saleinfo = saleinfo;
    }

    public Housetype getHousetype() {
        return this.housetype;
    }
    
    public void setHousetype(Housetype housetype) {
        this.housetype = housetype;
    }

    public Purpose getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(Purpose purpose) {
        this.purpose = purpose;
    }

    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    public String getOtherreason() {
        return this.otherreason;
    }
    
    public void setOtherreason(String otherreason) {
        this.otherreason = otherreason;
    }

    public String getAdvice() {
        return this.advice;
    }
    
    public void setAdvice(String advice) {
        this.advice = advice;
    }

    public String getDealornot() {
        return this.dealornot;
    }
    
    public void setDealornot(String dealornot) {
        this.dealornot = dealornot;
    }
   








}